services:
  user-service:
    build: ./user-service
    ports:
      - "3000:3000"
    environment:
      DB_HOST: mysql
      DB_USER: root
      DB_PASSWORD: hassan12345
      DB_NAME: event_booking
    depends_on:
      - mysql

  event-service:
    build: ./event-service
    ports:
      - "3001:3001"
    environment:
      MONGO_URI: mongodb://mongodb:27017
    depends_on:
      - mongodb

  booking-service:
    build: ./booking-service
    ports:
      - "3002:3002"
    environment:
      DB_HOST: mysql
      DB_USER: root
      DB_PASSWORD: hassan12345
      DB_NAME: event_booking
      RABBITMQ_URL: amqps://dvbqimoe:vDgguisUVHY2Kme9uEMu8O8w21HnkS6V@jackal.rmq.cloudamqp.com/dvbqimoe
    depends_on:
      - mysql
      - rabbitmq

  notification-service:
    build: ./notification-service
    ports:
      - "3003:3003"
    environment:
      RABBITMQ_URL: amqps://dvbqimoe:vDgguisUVHY2Kme9uEMu8O8w21HnkS6V@jackal.rmq.cloudamqp.com/dvbqimoe
    depends_on:
      - rabbitmq

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: hassan12345
      MYSQL_DATABASE: event_booking
    ports:
      - "3307:3306"

  mongodb:
    image: mongo:6.0
    ports:
      - "27017:27017"

  rabbitmq:
    image: rabbitmq:3.12-management
    ports:
      - "5672:5672"
      - "15672:15672"
